package entidades.Ruta;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import entidades.Usuario.Usuario;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer idRuta;
     private Usuario usuario;
     private Date fecha;
     private String descripcion;
     private Float latitudOrigen;
     private Float longitudOrigen;
     private Float latitudDestino;
     private Float longitudDestino;
     private Set solicituds = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Date fecha) {
        this.fecha = fecha;
    }
    public Ruta(Usuario usuario, Date fecha, String descripcion, Float latitudOrigen, Float longitudOrigen, Float latitudDestino, Float longitudDestino, Set solicituds) {
       this.usuario = usuario;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.latitudOrigen = latitudOrigen;
       this.longitudOrigen = longitudOrigen;
       this.latitudDestino = latitudDestino;
       this.longitudDestino = longitudDestino;
       this.solicituds = solicituds;
    }
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getLatitudOrigen() {
        return this.latitudOrigen;
    }
    
    public void setLatitudOrigen(Float latitudOrigen) {
        this.latitudOrigen = latitudOrigen;
    }
    public Float getLongitudOrigen() {
        return this.longitudOrigen;
    }
    
    public void setLongitudOrigen(Float longitudOrigen) {
        this.longitudOrigen = longitudOrigen;
    }
    public Float getLatitudDestino() {
        return this.latitudDestino;
    }
    
    public void setLatitudDestino(Float latitudDestino) {
        this.latitudDestino = latitudDestino;
    }
    public Float getLongitudDestino() {
        return this.longitudDestino;
    }
    
    public void setLongitudDestino(Float longitudDestino) {
        this.longitudDestino = longitudDestino;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


