package entidades.Noticia;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import entidades.Usuario.Usuario;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Noticia generated by hbm2java
 */
public class Noticia  implements java.io.Serializable {


     private Integer idNoticia;
     private Usuario usuario;
     private String descripcion;
     private Date fecha;
     private Set comentarios = new HashSet(0);

    public Noticia() {
    }

	
    public Noticia(Date fecha) {
        this.fecha = fecha;
    }
    public Noticia(Usuario usuario, String descripcion, Date fecha, Set comentarios) {
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
    public Integer getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(Integer idNoticia) {
        this.idNoticia = idNoticia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


