package entidades.Auto;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Auto generated by hbm2java
 */
public class Auto  implements java.io.Serializable {


     private Integer idAuto;
     private String matricula;
     private String color;
     private String marca;
     private String modelo;
     private int capacidad;
     private Set usuarios = new HashSet(0);

    public Auto() {
    }

    public Auto(String matricula, String color, String marca, String modelo,int capacidad, Set usuarios) {
       this.matricula = matricula;
       this.color = color;
       this.marca = marca;
       this.modelo = modelo;
       this.capacidad = capacidad;
       this.usuarios = usuarios;
    }
   
    public Integer getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(Integer idAuto) {
        this.idAuto = idAuto;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public int getCapacidad() {
        return capacidad;
    }
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return "Auto{" + "idAuto=" + idAuto + ", matricula=" + matricula + ", color=" + color + ", marca=" + marca + ", modelo=" + modelo + ", capacidad=" + capacidad + ", usuarios=" + '}';
    }

}


