package entidades.Usuario;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0

import entidades.Auto.Auto;




/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Auto auto;
     private String user;
     private String pass;
     private String nombre;
     private String apellido;
     private String direccion;
     private Character sexo;
     private String email;
     private String telefono;
     private String celular;

    public Usuario() {
    }

    public Usuario(Auto auto, String user, String pass, String nombre, String apellido, String direccion, Character sexo, String email, String telefono, String celular) {
       this.auto = auto;
       this.user = user;
       this.pass = pass;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.sexo = sexo;
       this.email = email;
       this.telefono = telefono;
       this.celular = celular;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Auto getAuto() {
        return this.auto;
    }
    
    public void setAuto(Auto auto) {
        this.auto = auto;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", auto=" + auto + ", user=" + user + ", pass=" + pass + ", nombre=" + nombre + ", apellido=" + apellido + '}';
    }

}


