package entidades.Solicitud;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import entidades.Estado.Estado;
import entidades.Ruta.Ruta;
import entidades.Usuario.Usuario;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Ruta ruta;
     private Estado estado;
     private Usuario usuario;
     private Float latitud;
     private Float longitud;

    public Solicitud() {
    }

    public Solicitud(Ruta ruta, Estado estado, Usuario usuario, Float latitud, Float longitud) {
       this.ruta = ruta;
       this.estado = estado;
       this.usuario = usuario;
       this.latitud = latitud;
       this.longitud = longitud;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }




}


