package entidades.Imagen;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import entidades.Usuario.Usuario;

/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer idImagen;
     private Usuario usuario;
     private String src;

    public Imagen() {
    }

    public Imagen(Usuario usuario, String src) {
       this.usuario = usuario;
       this.src = src;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }




}


