package entidades.Amistad;
// Generated 13-ago-2014 2:25:45 by Hibernate Tools 3.6.0


import entidades.Usuario.Usuario;

/**
 * Amistad generated by hbm2java
 */
public class Amistad  implements java.io.Serializable {


     private Integer idAmistad;
     private Usuario usuarioByUser1;
     private Usuario usuarioByUser2;

    public Amistad() {
    }

    public Amistad(Usuario usuarioByUser1, Usuario usuarioByUser2) {
       this.usuarioByUser1 = usuarioByUser1;
       this.usuarioByUser2 = usuarioByUser2;
    }
   
    public Integer getIdAmistad() {
        return this.idAmistad;
    }
    
    public void setIdAmistad(Integer idAmistad) {
        this.idAmistad = idAmistad;
    }
    public Usuario getUsuarioByUser1() {
        return this.usuarioByUser1;
    }
    
    public void setUsuarioByUser1(Usuario usuarioByUser1) {
        this.usuarioByUser1 = usuarioByUser1;
    }
    public Usuario getUsuarioByUser2() {
        return this.usuarioByUser2;
    }
    
    public void setUsuarioByUser2(Usuario usuarioByUser2) {
        this.usuarioByUser2 = usuarioByUser2;
    }

    @Override
    public String toString() {
        return "Amistad{" + "idAmistad=" + idAmistad + ", usuarioByUser1=" + usuarioByUser1 + ", usuarioByUser2=" + usuarioByUser2 + '}';
    }

}


